// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF2bRAtYkaLt_VQNt38adNQYNJyaQzlPE',
    appId: '1:174550892287:web:77e35da2af6e89698f56ca',
    messagingSenderId: '174550892287',
    projectId: 'phone-otp12842',
    authDomain: 'phone-otp12842.firebaseapp.com',
    storageBucket: 'phone-otp12842.appspot.com',
    measurementId: 'G-JZSFF6BGF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOXzrdT3xeSXsCoLYwVTvTDC061iRVHc',
    appId: '1:174550892287:android:597dd484a73ecfc18f56ca',
    messagingSenderId: '174550892287',
    projectId: 'phone-otp12842',
    storageBucket: 'phone-otp12842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBILemN_Jl16ywi4nyrShgbAacY_7xM4M0',
    appId: '1:174550892287:ios:319f283a97f6b40d8f56ca',
    messagingSenderId: '174550892287',
    projectId: 'phone-otp12842',
    storageBucket: 'phone-otp12842.appspot.com',
    androidClientId: '174550892287-e37tefblmpvl6egtar8asmvgbbfo83mh.apps.googleusercontent.com',
    iosClientId: '174550892287-ic7f2qt4nvrn9in9ls0hrorejp81ceau.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneNumberOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBILemN_Jl16ywi4nyrShgbAacY_7xM4M0',
    appId: '1:174550892287:ios:319f283a97f6b40d8f56ca',
    messagingSenderId: '174550892287',
    projectId: 'phone-otp12842',
    storageBucket: 'phone-otp12842.appspot.com',
    androidClientId: '174550892287-e37tefblmpvl6egtar8asmvgbbfo83mh.apps.googleusercontent.com',
    iosClientId: '174550892287-ic7f2qt4nvrn9in9ls0hrorejp81ceau.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneNumberOtp',
  );
}
